omletbot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sites.urls')),
]

sites/urls.py
from django.urls import path
from . import views
handler404 = 'sites.views.handler404'
app_name="sites"
urlpatterns = [
    path('', views.home, name="home"),
    path('error/', views.error, name="error"),
    path('api/', views.api,name='api'),
    path('shop/', views.shop,name='shop'),
    path('freetrial/',views.freetrial,name='freetrial')
]

sites/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class List(models.Model):
    id = models.AutoField(primary_key=True)
    ft_follow   = models.CharField(max_length=120,default='NULL')
    ft_view   = models.CharField(max_length=120,default='NULL')
    ft_like   = models.CharField(max_length=120,default='NULL')
    follow   = models.CharField(max_length=120,default='NULL')
    view   = models.CharField(max_length=120,default='NULL')
    like   = models.CharField(max_length=120,default='NULL')

# # Create your models here.
# class FreeTrialFollow(models.Model):
#     id = models.AutoField(primary_key=True)
#     username   = models.CharField(max_length=120,default='NULL')
#     time   = models.CharField(max_length=120,default='NULL')
    
# # Create your models here.
# class FreeTrialView(models.Model):
#     id = models.AutoField(primary_key=True)
#     username   = models.CharField(max_length=120,default='NULL')
#     time   = models.CharField(max_length=120,default='NULL')
    

class Bots(models.Model):
    id = models.AutoField(primary_key=True)
    username   = models.CharField(max_length=120,default='NULL')
    kind        = models.IntegerField(default=0)
    name        = models.CharField(max_length=120,default='NULL')
    time   = models.CharField(max_length=120,default='NULL')

class Queue(models.Model):
    username   = models.CharField(max_length=120,default='NULL',unique=True)
    kind        = models.IntegerField(default=0)
    time   = models.CharField(max_length=120,default='NULL')
class Proxies(models.Model):
    proxy= models.CharField(max_length=120,unique=True,null=False)
    active = models.BooleanField(default=True)
class Count(models.Model):
    name=models.CharField(max_length=120,unique=True,null=False)
    count=models.IntegerField(null=False,default=0)

sites/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404 
from .models import List, Bots, Queue, Proxies, Count

from django.views.decorators.csrf import csrf_exempt, csrf_protect

# from __future__ import division
from datetime import datetime, timedelta
import string

def totimestamp(dt, epoch=datetime(1970,1,1)):
    td = dt - epoch
    # return td.total_seconds()
    return (td.microseconds + (td.seconds + td.days * 86400) * 10**6) / 10**6 


import json
title = "Omlet Arcade Bot"
my_list=[ 
    {"title": "FREE TRIAL VIEW BOTS","url":"sites.views.freetrial","urls":"sites:freetrial","count":0,"used":0},
    {"title":"VIEW BOTS","url":"sites.views.shop","urls":"sites:shop","count":0,"used":0}
    ]
nav_list=[
    {"title": "FREE TRIAL", "urls": "sites:freetrial"},{"title":"SHOP","urls":"sites:shop"}
]

paypal_client_id="Acy2-a8xPnuhXCCNVWIucs4gE-sfstuo6s2QMOgHcJOKJAaw2xby0UhTsWLr2Tl4TUsxyXqe1H-C-z2z"
paypal_secret_id="ECYVwZ7GCoITw81qJFasaLU8xNfu4PhnIO1NRUJaqPi9HS_JITu3-M5rholwZMjAsypJOvgrlwVDrEEf"



def GetCount():
    # data = 0
    a=1
    b=2
    c=3
    d=5
    try:
        query = Count.objects.get(name='freetrial-visit')
        my_list[0]["count"] = query.count
        query = Count.objects.get(name='shop-visit')
        my_list[1]["count"] = query.count
    except Exception as e:
        print("ERROR: " + str(e))
        pass
    # return data


def home(request):
    GetCount()
    nav = "."
    isnav = ""
    site="home"
    # now = datetime.utcnow()
    # now=totimestamp(now)
    # article = List()
    # article.ft_follow = str(now)
    # article.ft_view = str(now)
    # article.ft_like = str(now)
    # article.save()
    
    # follow = List.objects.get(id=1).ft_follow
    # print(follow)
    return render(
        request, 
        'sites/home.html', 
        {
            'title':title, 
            'nav':nav, 
            'isnav': isnav,
            'my_list':my_list,
            'nav_list':nav_list
        }
    )

@csrf_exempt
def freetrial(request):
    GetCount()
    nav = "."
    isnav = ""
    site="freetrial"

    @csrf_protect
    def protected_path(request):
        pass
    if request.method=='POST':
        protected_path(request)

    return render(
        request, 
        'sites/freetrial.html', 
        {
            'title': title, 
            'nav': nav, 
            'isnav': isnav,
            'site': site,
            'my_list': my_list,
            'nav_list': nav_list
        }
    )

def shop(request):
    GetCount()
    nav = "."
    isnav = ""
    site="shop"
    if request.method=='POST':
        pass
    return render(request, 
    'sites/shop.html', 
    {'title':title, 
    'nav':nav, 
    'isnav': isnav,
    'site':site,
    'my_list':my_list,
    'nav_list':nav_list, 
    'paypal_client_id':paypal_client_id
    }
    )
def error(request):
    source = "."
    return render(request, 'sites/error.html', {'title':title, 'source':source})

def api(request):
    if request.method == 'GET':
        
        if request.GET.get('q')=="fgfz544wbw46b4wbb4":



            if request.GET.get('number'):
                if request.GET.get('number').isdigit():
                    number=int(request.GET.get('number'))
                    y = get_offline_bot(number)
                    return HttpResponse(y)
                
                elif request.GET.get('test')=='true':

                    # query = List.objects.get(id=2)
                    # query.follow=query.ft_follow
                    # query.like=query.ft_follow
                    # query.view=query.ft_follow
                    # query.save()
                    
                    query = List.objects.get(id=2)
                    data={
                        "freetrial_follow": query.ft_follow,
                        "freetrial_like": query.ft_like,
                        "freetrial_view": query.ft_view,
                        "follow": query.follow,
                        "like": query.like,
                        "view": query.view,
                    } 


                    y = json.dumps(data)

            
                    return HttpResponse(y)
    source = "."
    return render(request, 'sites/error.html', {'title':title, 'source':source})

def handler404(request, exception):
    return render(request, 'error.html', locals())


#### FUNCTIONS BEGIN
def get_offline_bot(number):
    status='NULL'
    query = Bots.objects.filter(name='NULL')
    if len(query)>0:
        for key, value in query.items():

            if 'name' in key:
                if query['kind'] == number:
                    status = value
                    break
    return status
#### FUNCTIONS END

sites/templates/sites/error.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta name="arcade-web-buildtime" content="Tue Dec 31 2019 09:51:17 GMT+0000 (UTC)">
        <meta name="arcade-web-version" content="2.1.14.146">
        <meta charset="utf-8">
        <meta name="ahrefs-site-verification" content="12087e3ea5805ca83cac9aab62259e4f861670b2e94b42db700de7744028f4d4">
        <title>{{ title }}</title>
        <link rel="apple-touch-icon" sizes="180x180" href="{% static '/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" href="{% static '/arcade-favicon-32x32.png' %}" sizes="32x32">
        <link rel="icon" type="image/png" href="{% static '/arcade-favicon-16x16.png' %}" sizes="16x16">
        <link rel="manifest" href="{% static 'manifest.json' %}">
        <link rel="mask-icon" href="{% static '/safari-pinned-tab.svg' %}" color="#e36a26">
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
        <meta name="theme-color" content="#ffffff">
        <link rel="canonical" href="https://omlet.gg/">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta property="og:locale" content="en_US">
        <meta property="og:locale:alternate" content="en_US">
        <meta property="og:locale:alternate" content="es_LA">
        <meta property="og:locale:alternate" content="pt_BR">
        <meta property="og:locale:alternate" content="zh_TW">
        <meta property="og:locale:alternate" content="zh_CN">
        <meta property="og:locale:alternate" content="ja_JP">
        <meta property="og:locale:alternate" content="ko_KR">
        <meta property="og:locale:alternate" content="id_ID">
        <meta property="og:locale:alternate" content="th_TH">
        <meta property="og:locale:alternate" content="vi_VN">
        <meta name="description" content="Omlet Arcade Bot is the largest mobile gaming and livestreaming bot community. Stream, buy bots, and win with fellow PUBG Mobile, Fortnite, Minecraft, Roblox, Mobile Legends, and Free Fire gamers today!">
        <meta property="fb:app_id" content="1000491693400315">
        <meta property="og:site_name" content="Omlet Arcade Bot – Mobile Game Livestreaming Bots">
        <meta property="og:url" content="https://omlet.gg/">
        <meta property="og:title" content="{{ title }}">
        <meta property="og:description" content="Omlet Arcade Bot is the largest mobile gaming and livestreaming bot community. Stream, buy bots, and win with fellow PUBG Mobile, Fortnite, Minecraft, Roblox, Mobile Legends, and Free Fire gamers today!">
        <meta property="og:type" content="website">
        <meta property="og:image" content="https://omlet.gg/img/og_default.png">
        <meta property="og:image:width" content="1200">
        <meta property="og:image:height" content="650">
        <meta name="twitter:site" content="@omletchat">
        <meta name="twitter:url" content="https://omlet.gg/">
        <meta name="twitter:title" content="{{ title }}">
        <meta name="twitter:description" content="Omlet Arcade Bot is the largest mobile gaming and livestreaming bot community. Stream, buy bots, and win with fellow PUBG Mobile, Fortnite, Minecraft, Roblox, Mobile Legends, and Free Fire gamers today!">
        <meta name="twitter:image" content="https://omlet.gg/img/og_default.png">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <style>
        body {background-color:black;font-family: arial, sans-serif;color:white;min-width:320px;}
        .center{text-align: center;}
        @-webkit-keyframes running {
          0% {
            background-image: url("{% static '/img/missing-arcade-1.png' %}");
          }
          50% {
            background-image: url("{% static '/img/missing-arcade-2.png' %}");
          }
        }

        .missing-image {
            display:inline-block;
            background-size: contain;
            background-image: url("{% static '/img/missing-arcade-1.png' %}");
            background-repeat: no-repeat;
            margin-top:101px;
            width: 278px;
            height: 100px;

            -webkit-animation-name: running;
            -webkit-animation-duration: 0.2s;
            -webkit-animation-iteration-count: infinite;
            -webkit-animation-direction: reverse;
            -webkit-animation-timing-function: linear;
        }

        .missing-text-block {
            margin-top:48px;
        }
        .missing-text-block h1 {
            margin:40px;
            font-size: 30px;
            font-weight: bold;
            margin-bottom: 0px;
        }
        .missing-text-block p {
            font-size: 22px;
            margin-top: 0px;
            margin-bottom: 50px;
        }
        .home-button {
            min-width: 200px;
            height: 40px;
            text-align: center;
            color: white;
            font-size: 18px;
            border-color: #ff6948;
            border-radius: 4px;
            background-color: #ff6948;
            cursor:pointer;
        }
        .home-button:hover {
            opacity: 0.8;
        }
        .arcade-logo {
            width: 224px;
            height: 24px;
            background-size: contain;
            background-repeat: no-repeat;
            background-image: url("{% static '/img/missing-arcade-logo.png' %}");
            position: absolute;
            bottom: 20px;
            left: 50%;
            transform: translateX(-50%);
        }
    </style>
<script>


</script>
</head>
<body>
<div class="center">
    <div class="missing-image"></div>
    <div class="missing-text-block">
        <h1>Page not found</h1>
        <p>Sorry, this page does not exist :(</p>
    </div>
    <a href="{% url 'sites:home' %}">
        <button class="home-button">HOME</button>
    </a>
    <a href="{% url 'sites:home' %}">
        <div class="arcade-logo"></div>
    </a>
</div>



</body>
</html>

sites/templates/sites/freetrial.html
{% extends "sites/index.html" %}
{% block content %}

<style>

    .stream-settings-view .setting-panel {
        box-shadow: 0px 3px 14px 0 rgba(0,0,0,0.5);
        margin-bottom: 12px;
    }
    .stream-settings-view .header {
        width: 100%;
        height: 48px;
        margin-top: 16px;
        background-color: #232533;
        text-align: left;
        text-indent: 20px;
        line-height: 48px;
        font-size: 16px;
        font-weight: bold;
        color: #ffffff;
        font-family: Helvetica;
    }
    
    .stream-settings-view .content-area {
        width: 100%;
        background-color: #2d2f41;
        overflow: hidden;
    }
    
    .stream-settings-view .setting-section {
        position: relative;
        border: solid 1px #737485;
        border-radius: 4px;
        margin: 0 8px 8px 0;
    }
    
    .settings-content {
        width: 100%; 
        margin-left: 0px;
        margin-top: 0px;
    }
    .stream-settings-container {
    min-width: 0px;
    }
    
    </style>
    <script 
    src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
    </script>
    <div class="content-wrapper post-container" >
        <div class="post-user-info-bar" style="padding: 16px 10px 8px 16px;text-align: left;">
            <span>
                
            </span>
    
            <div class="user-text-content">
                <a href="#">
                    <div class="user-name clickable" title="mr.robot">
                        <div class="user-post-name">Mr. ROBOT
    
                        </div>
                    </div>
                </a>
                <span>BOT · 24/H</span>
            </div>
            <div class="more-icon" title="Report this post">
    
            </div>
    
                
        </div>
        <div style="text-align: center;" class="post-title clamp clamp-three-lines" title="Buy Bots Now">Free Trial Bots Now
        </div>
    
        <div class="content-post">
            <div class="rich-post-content">
                <div class="rich-text block" style="text-align: center;">
                    <pre style="white-space: pre-wrap; overflow-wrap: break-word; line-height: 1.5; display: inline-block; width: 100%; font-family: Roboto; color: rgb(255, 255, 255); font-size: 16px;">
                        All bots are working for 1 hour. So keep that in mind. Also if you make a mistake with your username then you must contact me to get support or your payment is lost.
                    </pre>
                </div>
            </div>
        </div>
    
    
        
    </div>
    <div class="stream-settings-container" style="width: 100%;/*min-width: 792px;*/">
    <div class="settings-content">
    <div class="stream-settings-view">
    <div class="setting-panel">
        <div class="header">Bots</div>
        <div class="content-area">
            <div class="content-wrap" style="width: 100%;">
                <div class="left-lane stream-settings"style="width:calc(100% - 10px);float:none;margin-left: 5px;">
    
                    <div class="setting-section desc-block">
                        <div class="title">View 1 Hour / 5 Bots / Free Trial</div>
                        <form name="input" target="_self" action="{% url 'sites:freetrial' %}" method="post">
                            {% csrf_token %}
                            <input placeholder="Add your Username" name="username" value=""style="width:45%;">
                            <input type="hidden" name="freetrial" value="5view">
                            <input style="/*margin: 5px 0px 5px 0px;*/width: 120px;" class="btn"type="submit" alt="Submit">
                            
                        </form>
                        <!--textarea>Watch me play on Omlet Arcade! https://omlet.gg/iceman994</!--textarea-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>

{% endblock content %}

sites/templates/sites/home.html
{% extends "sites/index.html" %}
{% block content %}

<div class="content-wrapper post-container" >
    <div class="post-user-info-bar" style="padding: 16px 10px 8px 16px;text-align: left;">
        <span>
            
        </span>

        <div class="user-text-content">
            <a href="#">
                <div class="user-name clickable" title="mr.robot">
                    <div class="user-post-name">Mr. ROBOT

                    </div>
                </div>
            </a>
            <span>BOT · 24/H</span>
        </div>
        <!--div-- class="more-icon" title="Report this post">

        </!--div-->
    </div>
    <div style="text-align: center;" class="post-title clamp clamp-three-lines" title="Ki mit tud androidon az internal audio -ról?">
        
    </div>
    <div class="content-post">
        <div class="rich-post-content">
            <div class="rich-text block" style="text-align: left;">
                <pre style="white-space: pre-wrap; overflow-wrap: break-word; line-height: 1.5; display: inline-block; width: 100%; font-family: Roboto; color: rgb(255, 255, 255); font-size: 16px;">We're not kidding. You can compare if you'd like. If you've tried other Omlet Arcade Bots, you'll know, they fluctuate a lot, and it's annoying. They typically sell it as "fluctuation looks normal" or "we do it to make it look natural", but we know that's a lie. We know that their Omlet Arcade Bot is just unstable. Our viewbot, though, none of that! We have worked hard to make sure the delivery you ask for is the delivery you get, and especially on smaller Omlet Arcade channels, you'll notice the solid, stable delivery.
                </pre>
            </div>
        </div>
    </div>
    <div class="post-buff-detail-container__post-buff-detail__3_JLw">
        <img style="width: 120px;height: 120px;" src="/static/aw/img/arcade-logo.png" class="high-five-img__post-buff-detail__3XDUJ" role="presentation">
        <p class="text__post-buff-detail__12sUX" style="white-space: pre-wrap;">If you love our bots buy more or share with your friends. If more people buy we grew bigger and you will get super exclusive bots.</p>
    </div>
</div>

{% endblock content %}

sites/templates/sites/list.html
{% load static %}
{% if my_list %}
{% for items in my_list %}
<a class="trending-game-card__trending-game-card__1IA-4" href="{% url items.urls %}">
    <div class="app-icon-container__trending-game-card__MndDC">
        <img src="{% static '/aw/img/arcade-logo.png' %}" class="app-icon__trending-game-card__qf-6B">
    </div>
    <h1 class="name__trending-game-card__1Smxs clamp clamp-two-lines"style="white-space: pre-wrap;">{{ items.title }}</h1>
    <p class="member-count__trending-game-card__22sfi">
        <img class="count-icon__trending-game-card__1n3HQ" src="{% static '/aw/img/oi_member.png' %}" role="presentation">{{ items.count }}
    </p>
    <p class="post-count__trending-game-card__3lU9q">
        <img class="count-icon__trending-game-card__1n3HQ" src="{% static '/aw/img/oi_post.png' %}" role="presentation">{{ items.used }} paid
    </p>
</a>
{% endfor %}
{% endif %}

sites/templates/sites/shop.html
{% extends "sites/index.html" %}
{% block content %}

<style>

.stream-settings-view .setting-panel {
    box-shadow: 0px 3px 14px 0 rgba(0,0,0,0.5);
    margin-bottom: 12px;
}
.stream-settings-view .header {
    width: 100%;
    height: 48px;
    margin-top: 16px;
    background-color: #232533;
    text-align: left;
    text-indent: 20px;
    line-height: 48px;
    font-size: 16px;
    font-weight: bold;
    color: #ffffff;
    font-family: Helvetica;
}

.stream-settings-view .content-area {
    width: 100%;
    background-color: #2d2f41;
    overflow: hidden;
}

.stream-settings-view .setting-section {
    position: relative;
    border: solid 1px #737485;
    border-radius: 4px;
    margin: 0 8px 8px 0;
}

.settings-content {
    width: 100%; 
    margin-left: 0px;
    margin-top: 0px;
}

</style>
<script 
src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}"> // Required. Replace SB_CLIENT_ID with your sandbox client ID.
</script>
<div class="content-wrapper post-container" >
    <div class="post-user-info-bar" style="padding: 16px 10px 8px 16px;text-align: left;">
        <span>
            
        </span>

        <div class="user-text-content">
            <a href="#">
                <div class="user-name clickable" title="mr.robot">
                    <div class="user-post-name">Mr. ROBOT

                    </div>
                </div>
            </a>
            <span>BOT · 24/H</span>
        </div>
        <div class="more-icon" title="Report this post">

        </div>

            
    </div>
    <div style="text-align: center;" class="post-title clamp clamp-three-lines" title="Buy Bots Now">Buy Bots Now
    </div>

    <div class="content-post">
        <div class="rich-post-content">
            <div class="rich-text block" style="text-align: center;">
                <pre style="white-space: pre-wrap; overflow-wrap: break-word; line-height: 1.5; display: inline-block; width: 100%; font-family: Roboto; color: rgb(255, 255, 255); font-size: 16px;">
                    All bots are working for 1 hour. So keep that in mind. Also if you make a mistake with your username then you must contact me to get support or your payment is lost.
                </pre>
            </div>
        </div>
    </div>


    
</div>
<div class="stream-settings-container">
<div class="settings-content">
<div class="stream-settings-view">
<div class="setting-panel">
    <div class="header">Bots</div>
    <div class="content-area">
        <div class="content-wrap">
            <div class="left-lane stream-settings"style="width:100%;float:none;">

                <div class="setting-section desc-block">
                    <div class="title">View 1 Hour / 15 Bots / 10 €</div>
                    <form name="input" target="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="DNYW97HJ5XS6W">
                    <input type="hidden" name="on0" value="username">
                    <input placeholder="Add your Username" name="os0" value=""style="width:45%;">
                    <input style="background-color: transparent;/*margin: 5px 0px 5px 0px;*/width: 120px;"type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_buynow_SM.gif" border="0" alt="PayPal - The safer, easier way to pay online!">
                    </form>
                    <!--textarea>Watch me play on Omlet Arcade! https://omlet.gg/iceman994</!--textarea-->
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
{% endblock content %}